Convert heiko to pip package
k4cg/heiko pull request #57
Opened 2019-10-10 21:20 UTC by noqqe

* moved Markdown to RST (required by PYPI)
* Initialized setup.py with metadata
* Added release.sh (if on master, you can release a new version to pypi)
* Removed heiko-cli. Its not needed anymore and replaced by heiko module internal main() function

After this is merged, configuration changes on the matomat laptop are required (agetty, passwd, ...)

2019-10-14 19:57 UTC, blarz requested changes

2019-10-14 19:57 UTC, blarz commented on heiko/__init__.py
> +    maas_cfg = heiko.MaaSConfig(conn_str, cfg.get_maas_verify_ssl_certificates())
I needed to remove heiko. here

2019-10-14 19:57 UTC, blarz commented on heiko/__init__.py
> +    maas_builder = heiko.MaaSApiClientBuilder(maas_cfg)
Same here

2019-10-14 19:57 UTC, blarz commented on heiko/__init__.py
> +
Add a newline here

2019-10-14 19:57 UTC, blarz commented on heiko/__init__.py
> +
Too many blank lines here

2019-10-21 18:07 UTC, noqqe commented on heiko/__init__.py
> +    maas_cfg = heiko.MaaSConfig(conn_str, cfg.get_maas_verify_ssl_certificates())
resolved

2019-10-21 18:19 UTC, merged